GP_C_1_ProjectName-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home_page', as: 'home'

  get 'posts' => 'posts#index', as: 'posts'
  get 'forum' => 'forums#show', as: 'forum'
  get 'forum/new' => 'forums#new', as: 'forum/new'
  get 'forum/:forum/edit' => 'forums#edit', as: 'edit_forum'
  patch '/forum.:forum_id' => 'forums#update'
  post 'forum' => 'forums#create', :as => :create_forum
  delete "forum.:forum_id" => 'forums#destroy'
  forum_path = '/forum'
  get 'lobby' => 'lobby_requests#index', as: 'lobby'
  get 'about' => 'pages#about', as: 'about'
  get 'resources' => 'resources#index', as: 'resources'
  get 'profile' => 'profiles#index', as: 'profile'
  get 'messenger' => 'messengers#index', as: 'messenger'

  resources :lobby_requests
  resources :news_posts
  resources :announcements
  resources :posts do
    resources :comments
  end

end

GP_C_1_ProjectName-master/app/models/announcement.rb
class Announcement < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GP_C_1_ProjectName-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true,
                    length: {minimum: 1}
  validates :username, presence: true,
                    length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
  validates :name, presence: true,
                    length: {minimum: 5}
end

GP_C_1_ProjectName-master/app/models/lobby_request.rb
class LobbyRequest < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/news_post.rb
class NewsPost < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

GP_C_1_ProjectName-master/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  has_many :comments
  validates :title, presence: true,
                    length: {minimum: 5}

  validates :body, presence: true,
                   length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

GP_C_1_ProjectName-master/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :body)
    end
end

GP_C_1_ProjectName-master/app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = Forum.all
  end

  def new
    @forum = Forum.new
  end

  def show
    @forums = Forum.all
  end

  def create
    @forum = Forum.new(forum_params)

    if(@forum.save)
      redirect_to forum_path
    else
      render 'new'
    end
  end

  def edit
    @forum = Forum.find(params[:forum])
  end

  def update
    @forum = Forum.find(params[:forum_id])

    if(@forum.update(forum_params))
      redirect_to forum_path
    else
      render 'edit'
    end
  end

  def destroy
    @forum = Forum.find(params[:forum_id])

    if(@forum.posts != nil)
      @posts = @forum.posts
      @posts.each do |post|
        if(post.comments != nil)
          @comments = post.comments
          @comments.each do |comm|
            comm.destroy
          end
        end
        post.destroy
      end
    end
    @forum.destroy
    redirect_to forum_path
  end

  private def forum_params
    params.require(:forum).permit(:name)
  end

end

GP_C_1_ProjectName-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home_page
    @news_posts = NewsPost.all
    @announcements = Announcement.all
  end
end

GP_C_1_ProjectName-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def new
    @post =  Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.username = current_user.email

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if(@post.comments != nil)
      @comments = @post.comments
      @comments.each do |comm|
        comm.destroy
      end
        @post.destroy
    end
    redirect_to forum_path
  end

  private def post_params
    params.require(:post).permit(:username, :title, :body, :forum_id)
  end
end

GP_C_1_ProjectName-master/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

GP_C_1_ProjectName-master/app/helpers/application_helper.rb
module ApplicationHelper
end

GP_C_1_ProjectName-master/app/helpers/comments_helper.rb
module CommentsHelper
end

GP_C_1_ProjectName-master/app/helpers/forums_helper.rb
module ForumsHelper
end

GP_C_1_ProjectName-master/app/helpers/lobby_requests_helper.rb
module LobbyRequestsHelper

  def elapsedTime time
    elapsed = ((Time.now.hour*3600) + (Time.now.min*60) + (Time.now.sec)) - time
    if elapsed < 60
      output = (elapsed).to_s + "s"
    elsif elapsed < 3600
      output = (elapsed/60).to_s + "m"
    else
      ouput = (elapsed/3600).to_s + "h"
    end
    return output
  end

end

GP_C_1_ProjectName-master/app/helpers/messengers_helper.rb
module MessengersHelper
end

GP_C_1_ProjectName-master/app/helpers/news_posts_helper.rb
module NewsPostsHelper
end

GP_C_1_ProjectName-master/app/helpers/pages_helper.rb
module PagesHelper
end

GP_C_1_ProjectName-master/app/helpers/posts_helper.rb
module PostsHelper
end

GP_C_1_ProjectName-master/app/helpers/profiles_helper.rb
module ProfilesHelper
end

GP_C_1_ProjectName-master/app/helpers/resources_helper.rb
module ResourcesHelper
end

GP_C_1_ProjectName-master/app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :announcement_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :announcement_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

GP_C_1_ProjectName-master/app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

GP_C_1_ProjectName-master/app/views/announcements/index.html.erb
<h1>Announcements</h1>

<div class="card">
  <div class="card-body">
    <% @announcements.each do |announcement| %>


        <h5><%= announcement.title.truncate(40, separator: /\s/) %></h5>
        <p><%= announcement.body.truncate(200, omission: '...(continued)') %></p>
        <%= link_to 'Read More', announcement %>
        <!--<%= link_to 'Edit', edit_announcement_path(announcement) %>
        <%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %> -->

    <% end %>
</div>
</div>

<br>

<%= link_to 'Create New Announcement', new_announcement_path, :class => 'btn text-white btn-info' %>

<%= link_to 'Return To Home', home_path, :class => 'btn text-white btn-info' %>

GP_C_1_ProjectName-master/app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

GP_C_1_ProjectName-master/app/views/announcements/show.html.erb
<div class="card">
        <div class="card-body">

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
  <%= "(Posted on " + @announcement.created_at.to_s(:long) + ")" %>
</p>

<p>

  <%= simple_format(@announcement.body) %>
</p>
</div>
</div>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Delete', @announcement, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Return to Announcements', announcements_path %>