GP_C_1_ProjectName-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home_page', as: 'home'

  get 'posts' => 'posts#index', as: 'posts'
  get 'forum' => 'forums#show', as: 'forum'
  get 'forum/new' => 'forums#new', as: 'forum/new'
  get 'forum/:forum/edit' => 'forums#edit', as: 'edit_forum'
  patch '/forum.:forum_id' => 'forums#update'
  post 'forum' => 'forums#create', :as => :create_forum
  delete "forum.:forum_id" => 'forums#destroy'
  forum_path = '/forum'
  get 'lobby' => 'lobby_requests#index', as: 'lobby'
  get 'about' => 'pages#about', as: 'about'
  get 'resources' => 'resources#index', as: 'resources'
  get 'profile' => 'profiles#index', as: 'profile'
  get 'messenger' => 'messengers#index', as: 'messenger'

  resources :lobby_requests
  resources :news_posts
  resources :announcements
  resources :posts do
    resources :comments
  end

end

GP_C_1_ProjectName-master/app/models/announcement.rb
class Announcement < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GP_C_1_ProjectName-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true,
                    length: {minimum: 1}
  validates :username, presence: true,
                    length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
  validates :name, presence: true,
                    length: {minimum: 5}
end

GP_C_1_ProjectName-master/app/models/lobby_request.rb
class LobbyRequest < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/news_post.rb
class NewsPost < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

GP_C_1_ProjectName-master/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  has_many :comments
  validates :title, presence: true,
                    length: {minimum: 5}

  validates :body, presence: true,
                   length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

GP_C_1_ProjectName-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home_page
    @news_posts = NewsPost.all
    @announcements = Announcement.all
  end
end

GP_C_1_ProjectName-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def new
    @post =  Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.username = current_user.email

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if(@post.comments != nil)
      @comments = @post.comments
      @comments.each do |comm|
        comm.destroy
      end
        @post.destroy
    end
    redirect_to forum_path
  end

  private def post_params
    params.require(:post).permit(:username, :title, :body, :forum_id)
  end
end

GP_C_1_ProjectName-master/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

GP_C_1_ProjectName-master/app/helpers/application_helper.rb
module ApplicationHelper
end

GP_C_1_ProjectName-master/app/helpers/comments_helper.rb
module CommentsHelper
end

GP_C_1_ProjectName-master/app/helpers/forums_helper.rb
module ForumsHelper
end

GP_C_1_ProjectName-master/app/helpers/messengers_helper.rb
module MessengersHelper
end

GP_C_1_ProjectName-master/app/helpers/news_posts_helper.rb
module NewsPostsHelper
end

GP_C_1_ProjectName-master/app/helpers/pages_helper.rb
module PagesHelper
end

GP_C_1_ProjectName-master/app/helpers/posts_helper.rb
module PostsHelper
end

GP_C_1_ProjectName-master/app/helpers/profiles_helper.rb
module ProfilesHelper
end

GP_C_1_ProjectName-master/app/helpers/resources_helper.rb
module ResourcesHelper
end

GP_C_1_ProjectName-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GPC1Projectname</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <!-- <link href="sticky-footer-navbar.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="navbar.css" rel="stylesheet"> -->


  </head>

  <body class="body-background">

    <nav class="navbar navbar-expand navbar-dark fixed-top bg-dark border-bottom-0">
      <a class="navbar-brand" href="/">Overhead</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
          </ul>
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <%= link_to "Profile", '/profile', :class => 'btn card text-white bg-secondary' %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn card text-white bg-danger' %>
          </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-right">
            <%= link_to "Sign Up", '/users/sign_up', :class => 'btn card text-white bg-secondary' %>
            <%= link_to "Login", '/users/sign_in', :class => 'btn card text-white bg-secondary' %>
          </ul>
          <% end %>
      <!--
        <form id="signin" class="form-inline mt-2 mt-md-0">
          <div class="input-group">
            <!--<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>->
            <input id="email" type="email" class="form-control" name="email" value="" placeholder="Email Address">
          </div>
          <div class="input-group">
            <!--<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>->
            <input id="password" type="password" class="form-control" name="password" value="" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
          <%= link_to "Sign Up", '/users/sign_up', :class => 'btn btn-default' %>
        </form>
      -->
      </div>
    </nav>



    <nav class="navbar navbar-expand navbar-dark fixed-top bg-secondary" style="margin-top: 56px;">
      <a class="navbar-brand"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/lobby">Lobby</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/forum">Forum</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/resources">Resources</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">Contact Us</a>
          </li>
        </ul>
      </div>
    </nav>

    <% if notice %>
      <div class="container card bg-info text-white", style="margin-top: 56px; padding-top: 20px;">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="container card bg-danger text-white">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Project Overhead</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>
</html>

GP_C_1_ProjectName-master/app/views/pages/about.html.erb
<h1>About</h1>
<p>This is a placeholder contact and "about us" page for our webapp: "Overhead".</p>

GP_C_1_ProjectName-master/app/views/pages/home_page.html.erb
<h1>Welcome To Overhead!</h1>

<h6>A WebApp developed by Group GP_C_1 </h6>


<div class="card">
  <div class="card-body">
<table>
  <thead>
    <tr>
      <th>Announcements</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>

        <td><%= announcement.title.truncate(20, separator: /\s/) %></td>
        <td><%= announcement.body.truncate(140, omission: '...(continued)') %></td>
        <td>  <%= link_to 'View', announcement, :class => 'btn text-white btn-info' %> </td>
        <!--<%= link_to 'Edit', edit_announcement_path(announcement) %>
        <%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<%= link_to 'All Announcements', announcements_path, :class => 'btn text-white btn-info' %>



<div class="card">
  <div class="card-body">
<table>
  <thead>
    <tr>
      <th>News</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_posts.each do |news| %>
      <tr>

        <td><%= news.title.truncate(20, separator: /\s/) %></td>
        <td><%= news.body.truncate(140, omission: '...(continued)') %></td>
        <td><%= link_to 'View', news, :class => 'btn text-white btn-info' %></td>
        <!-- <td><= link_to 'Edit', edit_news_path(news), :class => 'btn btn-info' %></td>
        <td><%= link_to 'Delet', news, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<%= link_to 'All News', news_posts_path, :class => 'btn text-white btn-info' %>

GP_C_1_ProjectName-master/app/views/resources/index.html.erb
<h1>Resources</h1>
<p>This is a placeholder technical resources page for our webapp: "Overhead".</p>