GP_C_1_ProjectName-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home_page', as: 'home'

  get 'posts' => 'posts#index', as: 'posts'
  get 'forum' => 'forums#show', as: 'forum'
  get 'forum/new' => 'forums#new', as: 'forum/new'
  get 'forum/:forum/edit' => 'forums#edit', as: 'edit_forum'
  patch '/forum.:forum_id' => 'forums#update'
  post 'forum' => 'forums#create', :as => :create_forum
  delete "forum.:forum_id" => 'forums#destroy'
  forum_path = '/forum'
  get 'lobby' => 'lobby_requests#index', as: 'lobby'
  get 'about' => 'pages#about', as: 'about'
  get 'resources' => 'resources#index', as: 'resources'
  get 'profile' => 'profiles#index', as: 'profile'
  get 'messenger' => 'messengers#index', as: 'messenger'

  resources :lobby_requests
  resources :news_posts
  resources :announcements
  resources :posts do
    resources :comments
  end

end

GP_C_1_ProjectName-master/app/models/announcement.rb
class Announcement < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GP_C_1_ProjectName-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true,
                    length: {minimum: 1}
  validates :username, presence: true,
                    length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
  validates :name, presence: true,
                    length: {minimum: 5}
end

GP_C_1_ProjectName-master/app/models/lobby_request.rb
class LobbyRequest < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/news_post.rb
class NewsPost < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

GP_C_1_ProjectName-master/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  has_many :comments
  validates :title, presence: true,
                    length: {minimum: 5}

  validates :body, presence: true,
                   length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

GP_C_1_ProjectName-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])

    @comment = @post.comments.create(comment_params)
    @comment.username = current_user.email

    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @comment = @post.comments.find(params[:id])

    if(@comment.update(comment_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

GP_C_1_ProjectName-master/app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = Forum.all
  end

  def new
    @forum = Forum.new
  end

  def show
    @forums = Forum.all
  end

  def create
    @forum = Forum.new(forum_params)

    if(@forum.save)
      redirect_to forum_path
    else
      render 'new'
    end
  end

  def edit
    @forum = Forum.find(params[:forum])
  end

  def update
    @forum = Forum.find(params[:forum_id])

    if(@forum.update(forum_params))
      redirect_to forum_path
    else
      render 'edit'
    end
  end

  def destroy
    @forum = Forum.find(params[:forum_id])

    if(@forum.posts != nil)
      @posts = @forum.posts
      @posts.each do |post|
        if(post.comments != nil)
          @comments = post.comments
          @comments.each do |comm|
            comm.destroy
          end
        end
        post.destroy
      end
    end
    @forum.destroy
    redirect_to forum_path
  end

  private def forum_params
    params.require(:forum).permit(:name)
  end

end

GP_C_1_ProjectName-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home_page
    @news_posts = NewsPost.all
    @announcements = Announcement.all
  end
end

GP_C_1_ProjectName-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def new
    @post =  Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.username = current_user.email

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if(@post.comments != nil)
      @comments = @post.comments
      @comments.each do |comm|
        comm.destroy
      end
        @post.destroy
    end
    redirect_to forum_path
  end

  private def post_params
    params.require(:post).permit(:username, :title, :body, :forum_id)
  end
end

GP_C_1_ProjectName-master/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

GP_C_1_ProjectName-master/app/helpers/application_helper.rb
module ApplicationHelper
end

GP_C_1_ProjectName-master/app/helpers/comments_helper.rb
module CommentsHelper
end

GP_C_1_ProjectName-master/app/helpers/forums_helper.rb
module ForumsHelper
end

GP_C_1_ProjectName-master/app/helpers/lobby_requests_helper.rb
module LobbyRequestsHelper

  def elapsedTime time
    elapsed = ((Time.now.hour*3600) + (Time.now.min*60) + (Time.now.sec)) - time
    if elapsed < 60
      output = (elapsed).to_s + "s"
    elsif elapsed < 3600
      output = (elapsed/60).to_s + "m"
    else
      ouput = (elapsed/3600).to_s + "h"
    end
    return output
  end

end

GP_C_1_ProjectName-master/app/helpers/messengers_helper.rb
module MessengersHelper
end

GP_C_1_ProjectName-master/app/helpers/news_posts_helper.rb
module NewsPostsHelper
end

GP_C_1_ProjectName-master/app/helpers/pages_helper.rb
module PagesHelper
end

GP_C_1_ProjectName-master/app/helpers/posts_helper.rb
module PostsHelper
end

GP_C_1_ProjectName-master/app/helpers/profiles_helper.rb
module ProfilesHelper
end

GP_C_1_ProjectName-master/app/helpers/resources_helper.rb
module ResourcesHelper
end

GP_C_1_ProjectName-master/app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
<div class="card">
  <div class="card-body">
  <div class="container">
    <div class="row border-between">
    <!--  <div class="col-sm-2" style="padding-right:20spx; border-right: 1px solid #ccc;"> -->
    <div class="col-sm-2">
        <h6 class="userfont"><%= comment.username %></h6>
      </div>
      <div class="col-sm-10">
        <h6 class="titlefont">Re: <%= @post.title %></h6>
      </div>
    </div>
    <div class="row border-between">
    <!--  <div class="col-sm-2" style="padding-right:20spx; border-right: 1px solid #ccc;"> -->
    <div class="col-sm-2">
        <!--<p><strong><%= comment.username %></strong>-->
        <br><br>
        <%= link_to 'Edit', edit_post_comment_path(@post, comment), :class => 'btn btn-default' %>
        <%= link_to 'delet', [comment.post, comment],
                                          method: :delete,
                                          data: { confirm: 'delet this??'},
                                          :class => 'btn btn-danger' %>
      </div>
    <div class="col-sm-10">
      <%= simple_format(comment.body) %>
  </div>
</div>
</div>
</div>
</div>
<% end %>

GP_C_1_ProjectName-master/app/views/comments/_form.html.erb
<h3>Reply</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
  <!--  <%= f.label :username %><br> -->
    <%= f.hidden_field :username, :value => current_user.email %>
  </p>


  <p>
    <h6 class="userfont"><%= current_user.email %></h6>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-default'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/comments/edit.html.erb
<h1>Edit Reply</h1>
<%= form_for :comment, url: post_comment_path(@comment), method: :patch do |f| %>
  <%if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/forums/edit.html.erb
<h1>Edit Forum Name</h1>
<%= form_for :forum, url: forum_path(@forum), method: :patch do |f| %>
  <%if @forum.errors.any? %>
    <% @forum.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/forums/new.html.erb
<h1>Add Forum</h1>
<%= form_for :forum, url: forum_path do |f| %>
  <%if @forum.errors.any? %>
    <% @forum.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/forums/show.html.erb
<% @forums.each do |forum| %>
  <div class="card">
    <div class="card-body">
    <h1><%= forum.name %>

      <%= link_to 'Edit', edit_forum_path(forum), :class => 'btn btn-default' %>

         <%= link_to 'delet', forum_path(forum),
                                      method: :delete,
                                      data: { confirm: 'delet this??'},
                                      :class => 'btn btn-danger' %></h1>

    <% forum.posts.each do |post| %>
      <div class="card">
        <div class="card-body">
        <h3><%= post.title %></h3>
        <p><%= post.body.truncate(200, omission: '...(continued)') %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>
<% if user_signed_in? %>
<%= link_to "New Post", '/posts/new', :class => 'btn card text-white bg-secondary' %>
<%= link_to "New Forum", '/forum/new', :class => 'btn card text-white bg-secondary' %>

<% end %>

GP_C_1_ProjectName-master/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <%if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/posts/index.html.erb
<h1>Overhead</h1>
<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
    <h2><%= post.forum.name %></h2>
    <h3><%= post.title %></h3>
    <p><%= simple_format(post.body).truncate(200, omission: '...(continued)') %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

GP_C_1_ProjectName-master/app/views/posts/new.html.erb
<h1>Add Topic</h1>
<%= form_for :post, url: posts_path do |f| %>
  <%if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :forum %><br>
    <%= f.collection_select :forum_id, Forum.all, :id, :name %>
  </div>

<!--
  <p>
    <%= f.label :username %><br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
-->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>

GP_C_1_ProjectName-master/app/views/posts/show.html.erb
<h1><%= @post.forum.name %></h1>
<br>

<div class="card">
  <div class="card-body">
    <div class="container">
      <div class="row border-between">
        <div class="col-sm-2">
          <h6 class="userfont"><%= @post.username %></h6>
        </div>
        <div class="col-sm-10">
          <h6 class="titlefont"><%= @post.title %></h6>
      </div>
    </div>
    <div class="row border-between">
    <div class="col-sm-2">
        <br><br>
        <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default' %>
        <%= link_to 'delet', post_path(@post),
                                          method: :delete,
                                          data: { confirm: 'delet this??'},
                                          :class => 'btn btn-danger' %>
      </div>
    <div class="col-sm-10">
      <%= simple_format(@post.body) %>
  </div>
</div>
</div>
</div>
</div>

<!--
<h4><%= @post.username %></h4>
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>


<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "delet", post_path(@post),
                          method: :delete,
                          data: {confirm: 'delet this??'},
                          :class => 'btn btn-danger' %>
<hr>
-->

<br>
<%= render 'comments/comments' %>
<% if user_signed_in? %>
  <%= render 'comments/form' %>
<% end %>